TREE = MView/lib/Bio/MView/Align
DIRS = 
FILE =
EXES = 
SRCS = Consensus.pm Conservation.pm Header.pm Identity.pm Row.pm Ruler.pm \
       Sequence.pm
HTML = 

include $(HOME)/MView/etc/MAKEFILE.templ
