=pod

=head1 Synopsis

  my $sequence    #Bio::MView::Sequence instance
  my $from        #integer: start position of sequence for labelling
  my @list        #list of display rows

  #build an instance of an alignment object (mandatory arguments)

  my $a = new Bio::MView::Display($sequence);

  #build an instance of an alignment object (with extra parameters)

  my $b = new Bio::MView::Display($sequence, $from, @list);

  #add some display items to the $a object

  $a->append(@list);

  #explicitly add some (more?) display items to the $a object

  $a->append
      (

       { 'type'  => 'ruler' },

       { 'type'  => 'sequence',
	 'label1'=> 'first',
	 'url'   => 'http://fred.bloggs2',
	 'label2'=> 1.111,
	 'number'=> 1,
	 'range' => [ 1,  10, 'color'=>'red' ],
       },

       { 'type'  => 'subrange',
	 'label1'=> 'second',
	 'label2'=> 2.2,
	 'url'   => 'http://fred.bloggs',
	 'range' => [
		       1,  10, 'case'=>'uc','prefix'=>'<I>','suffix'=>'</I>',
		      15,  20, 'sym'=>'x','url'=>"URL1",
		      55, 104, 'sym'=>'*','url'=>"URL2",
		     100, 112, 'sym'=>'@','url'=>"URL3",
		    ],
       },

       { 'type'  => 'subrange',
	 'label1'=> 'third',
	 'label2'=> 3.14,
	 'range' => [
		      20, 100, 'color'=>'green' ],
		     500, 670, 'sym'=>'*','url'=>"URL4",
		     470, 510, 'color'=>'salmon',
		     800,1000, 'sym'=>'@',
		    ],
       },

       { 'type'  => 'subrange',
	 'label1'=> 'more data',
	 'label2'=> 4,
	 'range' => [
		      12, 314, 'sym'=>'h','color'=>'red',
		     200, 250, 'sym'=>'h','color'=>'red',
		     260, 260, 'sym='>'#',  #these two lines are equivalent
		          260, 'sym='>'#',  #this saves memory
		     328, 457, 'color'=>'purple',
		    ],
       },

      );

  #print the $a object using default formatting

  print $a->display;

  #print the $a object with some formatting overridden

  print $a->display('gap'=>'.', 'col'=>60, 'pad'=>' ', 'rec'=>"\n\n\n");


=head1 Defining a display list

A display list comprises a list of display items ordered as per the output
desired by the caller. Each display item may contain individual formatting
instructions for each subrange within. Currently, there are three types of
display item given by the 'type' attribute (see below).


 Attribute     Description
 -----------------------------------------------------------------------

 type          Mandatory. 'sequence' or 'subrange' or 'ruler', specifying
               the display of the parent sequence, some subranges thereof,
               or a simple ruler. Rulers count off 5, 10, 100's.

 label0        Optional. Zeroth label string of display item.

 label1        Optional. First label string of display item.

 label2        Optional. Second label string of display item.

 label3        Optional. Third label string of display item.

 label4        Optional. Fourth label string of display item.

 label5        Optional. Fifth label string of display item.

 label6        Optional. Sixth label string of display item.

 label7        Optional. Seventh label string of display item.

 url           Optional. URL to associate with 'label1'.

 number        Optional. If 1, attach sequence numbers to this item.

 sequence      Optional. Use supplied sequence instead of parent sequence
               as source of displayed characters. Must be same length as
               parent sequence.

 range         Optional. Any subranges of the parent sequence to be
               displayed for this display item, using optional formatting
               control attributes per subrange.

 paint         If paint=1 (default=0) then overlapping ranges for this row
               will use the colouring or symbol or URL of the last range
               definition in the region of the overlap as passed by the
               caller. The default behaviour is not to paint and to use the
               overlap symbol/colour (see below) or the last overlapping
               subrange by sequence order.

 prefix        if html, prefix whole row with this string.
 suffix        if html, suffix whole row with this string.

 pad           Pad character to fill leading/trailing empty space: overrides
               the display() pad setting for just this sequence.

The 'range' attribute is an anonymous array whose elements are also
anonymous arrays giving range and formatting information. Ranges can be
given in any order.  Each range consists minimally of a pair of ordered
integers indexing the parent sequence from 1, even if the actual labelling
for the parent sequence was specified differently.  An optional third
element after the range integer pair is an anonymous hash specifying
formatting details described below.



=head1 Formatting control: in display() call.

Display format control affecting the whole output is limited to:

 Attribute  Default      Behaviour
 -----------------------------------------------------------------------

 html       1            Controls HTML formatting {0=off,1=on}.

 bold       0            Embolden alignment

 col        80           Alignment width as number of columns. Setting
                         col < 1 causes the whole alignment to be
                         formatted as one long scrollable record.

 gap        '-'          Gap character to use.

 lap        '%'          Set the overlap character.
 lap        '#474747'    Set the overlap colour if html=1 and lap is more
                         than one character in length. Or set the overlap
                         character if html=1 and lap is just a single
                         character.

 pad        ''           Pad character to fill leading/trailing empty space.

 rec        "\n"         Record separator.

 ruler      'abs'        Controls ruler numbering: 'abs'= absolute from the
                         extreme left edge of the alignment, even if there
                         are marginal gaps. No other modes supported yet.

Overlaps can occur between subranges. If producing HTML, the display()
method will output the parent sequence in the overlap painted in the 'lap'
colour (defaulting to '#474747' [gray28] as above) or using the lap character
(defaulting to '%' as above). In non-HTML mode only the 'lap' character
will be printed. Clearly, if subranges overlap completely, all information
(colours, symbols, URLs) will be lost by this strategy. Alternatively, you
can simply ignore the cause of the overlap and continue with the new symbol
or colour or URL definitions by setting paint=1 for the whole row.  This is
useful for building up a complex image, for example, to define a long
subrange to be grey, then overlay some other colours at selected positions.



=head1 Formatting control: in subrange definitions.

Subrange format controls are:

 Attribute          Behaviour
 -------------------------------------------------------------------

 url                Embed range within this URL.

 sym                Use this symbol. Defaults to the parent sequence.

 case               Change range to case {uc|lc}. Ignored if 'sym' set.

 color              Set SPAN with this colour.

 class              Use SPAN.CLASS for this symbol.

 prefix		    Prefix with this arbitrary piece of HTML.

 suffix             Suffix with this arbitrary piece of HTML.



=head1 Example output

 <PRE>
		     [   .    :    .    :    .    :    .    :    .    :    .    :    .    :    .    :
 <A HREF="http://fred.bloggs2">first</A>     1.111   1 <SPAN style="color:red">GGAAATAAAA</SPAN>ATATAAAACCCGGTCGCAAGCGTGTCGCTGTAGATGAGCTGAAACGCAATTTTTCAGTGACTTTTTATCT  80
 <A HREF="http://fred.bloggs">second</A>      2.2     <I>GGAAATAAAA</I>----<A HREF="URL1">xxxxxx</A>----------------------------------<A HREF="URL2">**************************</A>
 third      3.14     -------------------<SPAN style="color:green">y5923y98y23v9t2 t oi2ltl3ntli2tit2309tu2905t2390tuvn 2u m t[3</SPAN>
 more data     4     -----------<SPAN style="color:red">hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh</SPAN>

			 .    :    .    |    .    :    .    :    .    :    .    :    .    :    .    :
 <A HREF="http://fred.bloggs2">first</A>     1.111  81 CTCTAAAGACGAGCGTAGAAAGCGTCAATTCTTTTGTCAAACGCCACATTTTAAAAACAATCATTTACAAAAAAGGCACT 160
 <A HREF="http://fred.bloggs">second</A>      2.2     <A HREF="URL2">*******************</A><SPAN style="color:#474747">AAGCG</SPAN><A HREF="URL3">@@@@@@@@</A>------------------------------------------------
 third      3.14     <SPAN style="color:green"> mv[ n[ 2  2   205g5</SPAN>------------------------------------------------------------
 more data     4     <SPAN style="color:red">hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh</SPAN>

			 .    :    .    :    .    :    .    |    .    :    .    :    .    :    .    :
 <A HREF="http://fred.bloggs2">first</A>     1.111 161 AACXAAGATTCTTCTATCAATTGTGATTCTTCTAGTAGGCTTTAAGCCTACTTTAAGGTATCAGCTCTTAAGAGCAGCAC 240
 <A HREF="http://fred.bloggs">second</A>      2.2     --------------------------------------------------------------------------------
 third      3.14     --------------------------------------------------------------------------------
 more data     4     <SPAN style="color:red">hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh</SPAN><SPAN style="color:#474747">CTTTAAGCCTACTTTAAGGTATCAGCTCTTAAGAGCAGCAC</SPAN>

			 .    :    .    :    .    :    .    :    .    :    .    |    .    :    .    :
 <A HREF="http://fred.bloggs2">first</A>     1.111 241 CCGCTAGAGCATTTAGTTTTAXTCCCTACCGATGAGCGATCCATCAAGCAAAACCAAACCCGGCCACAAACAAGCCTCCA 320
 <A HREF="http://fred.bloggs">second</A>      2.2     --------------------------------------------------------------------------------
 third      3.14     --------------------------------------------------------------------------------
 more data     4     <SPAN style="color:#474747">CCGCTAGAGC</SPAN><SPAN style="color:red">hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh</SPAN>------

			 .    :    .    :    .    :    .    :    .    :    .    :    .    :    .    |
 <A HREF="http://fred.bloggs2">first</A>     1.111 321 GCAAATAACGCXAAGTCTTTAACCACTAGCCAAAATAGCTATATGCATCAAATAGCCGCCTAAATTTTGAAGTTTTGTAA 400
 <A HREF="http://fred.bloggs">second</A>      2.2     --------------------------------------------------------------------------------
 third      3.14     --------------------------------------------------------------------------------
 more data     4     -------<SPAN style="color:purple">ACGCXAAGTCTTTAACCACTAGCCAAAATAGCTATATGCATCAAATAGCCGCCTAAATTTTGAAGTTTTGTAA</SPAN>

			 .    :    .    :    .    :    .    :    .    :    .    :    .    :    .    :
 <A HREF="http://fred.bloggs2">first</A>     1.111 401 TCACTXCAAGCAATGATTTTAACGCTTGCATGGTTTTATTCCTTTAGGATATTTTTTATATTGCTAAAAACAGCCTAGAA 480
 <A HREF="http://fred.bloggs">second</A>      2.2     --------------------------------------------------------------------------------
 third      3.14     ---------------------------------------------------------------------<SPAN style="color:salmon">GFKGFKFHFHF</SPAN>
 more data     4     <SPAN style="color:purple">TCACTXCAAGCAATGATTTTAACGCTTGCATGGTTTTATTCCTTTAGGATATTTTTT</SPAN>-----------------------

			 .    :    .    |    .    :    .    :  ]
 <A HREF="http://fred.bloggs2">first</A>     1.111 481 ATGATAGCGCATTATGTTTAATTXCAACAAAATCATTACTATT 523
 <A HREF="http://fred.bloggs">second</A>      2.2     -------------------------------------------
 third      3.14     <SPAN style="color:salmon">YTRU7r7r76576565576</SPAN><SPAN style="color:#474747">77%%AGCGCAT</SPAN><A HREF="URL4">*************</A>
 more data     4     -------------------------------------------

 </PRE>


=head1 Example output formatted

 <PRE>
		     [   .    :    .    :    .    :    .    :    .    :    .    :    .    :    .    :
 <A HREF="http://fred.bloggs2">first</A>     1.111   1 <SPAN style="color:red">GGAAATAAAA</SPAN>ATATAAAACCCGGTCGCAAGCGTGTCGCTGTAGATGAGCTGAAACGCAATTTTTCAGTGACTTTTTATCT  80
 <A HREF="http://fred.bloggs">second</A>      2.2     <I>GGAAATAAAA</I>----<A HREF="URL1">xxxxxx</A>----------------------------------<A HREF="URL2">**************************</A>
 third      3.14     -------------------<SPAN style="color:green">y5923y98y23v9t2 t oi2ltl3ntli2tit2309tu2905t2390tuvn 2u m t[3</SPAN>
 more data     4     -----------<SPAN style="color:red">hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh</SPAN>

			 .    :    .    |    .    :    .    :    .    :    .    :    .    :    .    :
 <A HREF="http://fred.bloggs2">first</A>     1.111  81 CTCTAAAGACGAGCGTAGAAAGCGTCAATTCTTTTGTCAAACGCCACATTTTAAAAACAATCATTTACAAAAAAGGCACT 160
 <A HREF="http://fred.bloggs">second</A>      2.2     <A HREF="URL2">*******************</A><SPAN style="color:#474747">AAGCG</SPAN><A HREF="URL3">@@@@@@@@</A>------------------------------------------------
 third      3.14     <SPAN style="color:green"> mv[ n[ 2  2   205g5</SPAN>------------------------------------------------------------
 more data     4     <SPAN style="color:red">hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh</SPAN>

			 .    :    .    :    .    :    .    |    .    :    .    :    .    :    .    :
 <A HREF="http://fred.bloggs2">first</A>     1.111 161 AACXAAGATTCTTCTATCAATTGTGATTCTTCTAGTAGGCTTTAAGCCTACTTTAAGGTATCAGCTCTTAAGAGCAGCAC 240
 <A HREF="http://fred.bloggs">second</A>      2.2     --------------------------------------------------------------------------------
 third      3.14     --------------------------------------------------------------------------------
 more data     4     <SPAN style="color:red">hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh</SPAN><SPAN style="color:#474747">CTTTAAGCCTACTTTAAGGTATCAGCTCTTAAGAGCAGCAC</SPAN>

			 .    :    .    :    .    :    .    :    .    :    .    |    .    :    .    :
 <A HREF="http://fred.bloggs2">first</A>     1.111 241 CCGCTAGAGCATTTAGTTTTAXTCCCTACCGATGAGCGATCCATCAAGCAAAACCAAACCCGGCCACAAACAAGCCTCCA 320
 <A HREF="http://fred.bloggs">second</A>      2.2     --------------------------------------------------------------------------------
 third      3.14     --------------------------------------------------------------------------------
 more data     4     <SPAN style="color:#474747">CCGCTAGAGC</SPAN><SPAN style="color:red">hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh</SPAN>------

			 .    :    .    :    .    :    .    :    .    :    .    :    .    :    .    |
 <A HREF="http://fred.bloggs2">first</A>     1.111 321 GCAAATAACGCXAAGTCTTTAACCACTAGCCAAAATAGCTATATGCATCAAATAGCCGCCTAAATTTTGAAGTTTTGTAA 400
 <A HREF="http://fred.bloggs">second</A>      2.2     --------------------------------------------------------------------------------
 third      3.14     --------------------------------------------------------------------------------
 more data     4     -------<SPAN style="color:purple">ACGCXAAGTCTTTAACCACTAGCCAAAATAGCTATATGCATCAAATAGCCGCCTAAATTTTGAAGTTTTGTAA</SPAN>

			 .    :    .    :    .    :    .    :    .    :    .    :    .    :    .    :
 <A HREF="http://fred.bloggs2">first</A>     1.111 401 TCACTXCAAGCAATGATTTTAACGCTTGCATGGTTTTATTCCTTTAGGATATTTTTTATATTGCTAAAAACAGCCTAGAA 480
 <A HREF="http://fred.bloggs">second</A>      2.2     --------------------------------------------------------------------------------
 third      3.14     ---------------------------------------------------------------------<SPAN style="color:salmon">GFKGFKFHFHF</SPAN>
 more data     4     <SPAN style="color:purple">TCACTXCAAGCAATGATTTTAACGCTTGCATGGTTTTATTCCTTTAGGATATTTTTT</SPAN>-----------------------

			 .    :    .    |    .    :    .    :  ]
 <A HREF="http://fred.bloggs2">first</A>     1.111 481 ATGATAGCGCATTATGTTTAATTXCAACAAAATCATTACTATT 523
 <A HREF="http://fred.bloggs">second</A>      2.2     -------------------------------------------
 third      3.14     <SPAN style="color:salmon">YTRU7r7r76576565576</SPAN><SPAN style="color:#474747">77%%AGCGCAT</SPAN><A HREF="URL4">*************</A>
 more data     4     -------------------------------------------

 </PRE>

=head1 Copyright (C) 1997-2006 Nigel P. Brown.

=cut
