TREE = lib/Bio/MView
DIRS = Align Build Display Option
FILE =
EXES = 
SRCS = Align.pm Build.pm Colormaps.pm Convert.pm Display.pm Manager.pm \
       Sequence.pm SRS.pm
HTML = 

include $(HOME)/etc/MAKEFILE.templ
