TREE = lib/Bio/MView
DIRS = Align Build Color Display Option
FILE =
EXES = 
SRCS = Align.pm Build.pm Convert.pm Display.pm GroupMap.pm Manager.pm \
       Sequence.pm SRS.pm
HTML = 

include $(HOME)/etc/MAKEFILE.templ
